version: '3'
services:

  test-db:
    container_name: test-db
    image: test-db
    build: ./db/
    ports:
      - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  test-flyway-cli:
    image: flyway/flyway
    container_name: test-flyway-cli
    command: -url=jdbc:mysql://test-db:3306/test_db -schemas=test_db -user=root -password=password -connectRetries=60 migrate
    volumes:
      - ./migrate/sql:/flyway/sql
    links:
      - test-db
volumes:
  test-db-volume: {}
